#First we print the list of students
puts "The students in my cohort at makers academy are: "
puts "------------"
puts "Abdul Hassan"
puts "Alan Bridger"
puts "Alexander Levin"
puts "Ana Nogal"
puts "Andrew Harrison"
puts "Andrew Hercules"
puts "Atilla Mirk"
puts "Claudia B"
puts "Colin Smif"
puts "Daniel Cotler"
puts "Ella Schofield"
puts "Elena Garone"
puts "Sandrine Zhang-Ferron"
puts "Tim Scully"
puts "Victoria Stepanova"
puts "Alex Blease"
#Then we print the number of students in the cohort
print "Overall we have "
print "15"
#This code snippet at the end illustrates that puts() includes a newline
#and print() doesn't
puts " great students."
