puts "The students in my cohort at makers academy are: "
puts "------------"
puts "Abdul Hassan"
puts "Alan Bridger"
puts "Alexander Levin"
puts "Ana Nogal"
puts "Andrew Harrison"
puts "Andrew Hercules"
puts "Atilla Mirk"
puts "Claudia B"
puts "Colin Smif"
puts "Daniel Cotler"
puts "Ella Schofield"
puts "Elena Garone"
puts "Sandrine Zhang-Ferron"
puts "Tim Scully"
puts "Victoria Stepanova"
puts "Alex Blease"

print "Overall we have "
print "15"
puts " great students."
